📚🩹 Fix conda env creation instructions (#13)
The conda env needs to also be created from the `conda-forge` channel or there might be ABI problems.

Avoid this issue when importing the package:
```
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
```

The updated guide was tested in a clean windows VM with only anaconda installed and it works for both the conda and pip installation methods.

---------

Co-authored-by: Joris Snellenburg <jsnel@users.noreply.github.com>